// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mspxqabklpoguqtmpkjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcHhxYWJrbHBvZ3VxdG1wa2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzQ1MDYsImV4cCI6MjA2OTg1MDUwNn0.DvCj7jS3C0ONV3KdcHMDjavppdYdrU63beM-WapPfts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});